-- ======================================================================
--[[	Show All Faction Relations in PDA
-- ======================================================================
	MCM initialization script
	Author: dEmergence (dEmergence @ ModDB)
	Source: https://www.moddb.com/mods/stalker-anomaly/addons/show-all-faction-relation-in-pda-except-monolith
	Version: 6.4.4
	Updated: 20250511

	Credits for code that I found helpful:

		TheMrDemonized, DoctorX for MCM Preset Selection Code
			As found in "[1.5.2/1.5.1] DYNAMIC ANOMALIES OVERHAUL (DAO)"
			https://www.moddb.com/mods/stalker-anomaly/addons/dynamic-anomalies-overhaul-dao-read-description-please

		ravenascendant for MCM table insert Code
			As found in "REPUTATION EDITOR (ANOMALY 1.5.1/1.5.2)"
			https://www.moddb.com/mods/stalker-anomaly/addons/reputation-editor

	This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License

-- ===================================================================--]]

function list_contains(t,value)
	for i = 1,#t do
		if t[i] == value then
			return true
		end
	end
	return false
end

factions_table = dup_table(game_relations.factions_table)

-- Безопасно добавляем Феникс в MCM-список фракций
if not list_contains(factions_table, "phoenix") then
    table.insert(factions_table, "phoenix")
end
--factions_table = game_relations.factions_table

if list_contains(game_relations.factions_table_all,"zombied") and not list_contains(factions_table,"zombied") then
	table.insert(factions_table,"zombied")
end

op_id = "dmg_safr_pda"

defaults = {
	["show_eliminated"] = true,
	["disable_squad_count"] = true,
	["show_local_squad_count"] = false,
	["obscure_enemy_squad_count"] = true,
	["use_encyclopedia_discovery"] = false,
	["debug_log"] = false,
	["show_mutant_faction"] = false,
	["user_preset"] = 1,
	["color_scheme"] = 1
}

presets = {
	[0] = {},
	[1] = {},
	[2] = {}
}

function Set(t,set_value)
  local s = {}
  for _,v in pairs(t) do s[v] = set_value end
  return s
end

if ui_mcm then
	function Patched_Callback_List(self, ctrl, path, opt, v)
		MCM_Callback_List(self, ctrl, path, opt, v)
		if path == op_id and opt == "user_preset" then
			local value = self:GetValue(path, opt, v)
			set_preset(self, value)
		end
	end
	if ui_mcm.UIMCM and ui_mcm.UIMCM.Callback_List then
		MCM_Callback_List = ui_mcm.UIMCM.Callback_List
		ui_mcm.UIMCM.Callback_List = Patched_Callback_List
	elseif ui_mcm.VERSION == "1.7.0" then
		MCM_Callback_List = ui_mcm.UI_MCM.Callback_List
		ui_mcm.UI_MCM.Callback_List = Patched_Callback_List
	end
end

function set_preset(self, p)
    if not presets[p] then
        printf("SAFR preset %s not found", p)
        return
	else
		printf("SAFR preset %s applied", p)
    end

    -- Pre-build available MCM values
    local t = {}
    for _, v in ipairs(op.gr) do
        if v.def ~= nil then
            t[v.id] = v.def
        end
    end

    for k, value in pairs(presets[p]) do
        if t[k] then

            -- Validate option
            local v = ui_mcm.get_opt_table(op_id .. "/" .. k)
            if v and v.type then

                -- Get proper value
                if v.val == 0 then
                    -- Pass input value as is
                elseif v.val == 1 then
                    value = (value == "true") and true or false
                elseif v.val == 2 then
                    value = clamp(tonumber(value), v.min or 0, v.max or 100)
                end

                -- Extract path and opt
                local t = ui_mcm.str_opt_explode(op_id .. "/" .. k)
                local opt = t[#t]
                local path = t[1]
                for i=2,#t-1 do
                    path = ui_mcm.cc(path , t[i])
                end

                -- Cache changes
                self:CacheValue(path, opt, value, v)
            end
        end
    end

    -- Update XML elements
    self:Reset_opt(self.last_curr_tree, self.last_path)

    -- Update state
    self:UpdatePending()
end

function set_presets()

	-- Populate Presets

	-- Anomaly Default Extended
	-- Set 'Do not show' for all then overwrite with default values
	presets[0] = Set(factions_table,0)
	presets[0]["stalker"] = 2
	presets[0]["bandit"] = 2
	presets[0]["csky"] = 2
	presets[0]["dolg"] = 2
	presets[0]["freedom"] = 2
	presets[0]["killer"] = 2
	presets[0]["army"] = 2
	presets[0]["ecolog"] = 2
	presets[0]["monolith"] = 2
	if level.present and db.actor then
		local actor_comm = string.gsub( character_community(db.actor), "actor_", "" )
		printf("SAFR: Actor community = "..actor_comm)
		presets[0][actor_comm] = 2
	end

	presets[1] = Set(factions_table,2)

	presets[2] = Set(factions_table,1)

end

function on_mcm_load()

	-- call populate
	set_presets()

	-- mcm menu code
	op = {id = "dmg_safr_pda", sh = true, gr = {}}

	tr = {
			{id = "title", type = "slide", link = "ui_options_slider_player", text = "ui_mcm_dmg_safr_pda_title", size = { 512, 50 }, spacing = 20 },
			{id = "show_eliminated", type = "check", val = 1, def = defaults["show_eliminated"]},
			{id = "disable_squad_count", type = "check", val = 1, def = defaults["disable_squad_count"]},
			{id = "show_local_squad_count", type = "check", val = 1, def = defaults["show_local_squad_count"]},
			{id = "obscure_enemy_squad_count", type = "check", val = 1, def = defaults["obscure_enemy_squad_count"]},
			{id = "divider", type="line" },
			{id = "use_encyclopedia_discovery", type = "check", val = 1, def = defaults["use_encyclopedia_discovery"]},
			{id = "debug_log", type = "check", val = 1, def = defaults["debug_log"]},
			{id = "show_mutant_faction", type = "check", val = 1, def = defaults["show_mutant_faction"]},
			{id = "divider", type="line" },
			{id = "color_scheme", type = "list", val = 2, def = defaults["color_scheme"],
				content= {
						{0,"ui_mcm_lst_SAFR_colors_default_anomaly"},
						{1,"ui_mcm_lst_SAFR_colors_expanded"},
						{2,"ui_mcm_lst_SAFR_colors_monochrome"}
					}
				},
			{id = "divider", type="line" },
			{id = "user_preset", type = "list", val = 2, def = defaults["user_preset"],
				content= {
						{0,"ui_mcm_lst_SAFR_default_anomaly"},
						{1,"ui_mcm_lst_SAFR_all_always"},
						{2,"ui_mcm_lst_SAFR_all_when_discovered"},
						{3,"ui_mcm_lst_SAFR_user_defined"}
					}
				},
			{id = "user_defined_desc", type = "desc", text = "ui_mcm_dmg_safr_pda_user_defined_desc_text"}
        }

	for i=1, #factions_table do
		table.insert(tr,  {id = factions_table[i], hint = "dcommontxt_factions_"..factions_table[i], type = "radio_h", val = 2, def = 1, content = { { 0, "ui_mcm_lst_SAFR_Never_show_faction" }, { 1, "ui_mcm_lst_SAFR_Show_faction_by_progression" }, { 2, "ui_mcm_lst_SAFR_Always_show_faction" } }})
	end

	-- title Pages Settings
	-- add page switches here

	op.gr = tr
	return op
end

function get_config(key)
	if ui_mcm then return ui_mcm.get(op_id.."/"..key) else return defaults[key] end
end

function on_game_load()
	set_presets()
end

function on_game_start()
	RegisterScriptCallback("on_game_load",on_game_load)
end
