function on_xml_read()
    RegisterScriptCallback("on_xml_read", function(xml_file_name, xml_obj)
        -- Ловим файл меню для 4:3 и 16:9
        if string.find(xml_file_name, "ui_mm_faction_select") then
            local phoenix_btn = [[
                <btn_faction_phoenix x="0" y="0" width="88" height="88" stretch="1">
                    <texture_e>ui_in_game2_phoenix</texture_e>
                    <texture_t>ui_in_game2_phoenix</texture_t>
                    <texture_h>ui_in_game2_phoenix</texture_h>
                </btn_faction_phoenix>
            ]]
            
            local res = xml_obj:query("popup_faction")
            if res and res[1] then
                xml_obj:insertFromXMLString(phoenix_btn, res[1], #res[1].kids)
            end
        end
    end)
end