-- Хук для регистрации кнопки Феникса в меню выбора фракции
local opt_init = ui_mm_faction_select.faction_select.InitControls

function ui_mm_faction_select.faction_select:InitControls(...)
    opt_init(self, ...)
    
    -- Проверяем, зарегистрирована ли уже кнопка
    if not self.btn_phoenix then
        -- Создаем кнопку UI из нашего XML
        self.btn_phoenix = self.xml:Init3tButton("faction_select:btn_faction_phoenix", self)
        
        -- Регистрируем событие клика
        self:Register(self.btn_phoenix, "btn_faction_phoenix")
        self:AddCallback("btn_faction_phoenix", ui_events.BUTTON_CLICKED, function()
            self:OnFactionSelect("phoenix")
        end)
    end
end